In [1]:
import pandas as pd
import numpy as np
from skimage.transform import rotate
from skimage.io import imread, imsave
from os.path import join
from random import shuffle
import warnings
warnings.filterwarnings("ignore")

In [2]:
df = pd.read_csv("data/train.rotfaces/train.truth.csv")
df.head()

                               fn          label
0  0-10049200_1891-09-16_1958.jpg   rotated_left
1  0-10110600_1985-09-17_2012.jpg   rotated_left
2  0-10126400_1964-07-07_2010.jpg        upright
3   0-1013900_1917-10-15_1960.jpg  rotated_right
4  0-10166400_1960-03-12_2008.jpg    upside_down

In [11]:
def data_augmentation(df):
    new_images = []
    for index, labels in df.iterrows():
        image_name = labels["fn"]
        label = labels["label"]
        
        image = imread(join("data", "train.rotfaces", "train", image_name))
        imsave(join("data","images", image_name), image)
        new_images.append({"fn": image_name, "label": label})
        
        
        if label == "upright":
            image_left = rotate(image, 90, preserve_range=True).astype(np.uint8)
            image_left_name = "up_left" + image_name
            imsave(join("data","images", image_left_name), image_left)
            new_images.append({"fn": image_left_name, "label": "rotated_left"})
            
            image_right = rotate(image, -90, preserve_range=True).astype(np.uint8)
            image_right_name = "up_right" + image_name
            imsave(join("data","images", image_right_name), image_right)
            new_images.append({"fn": image_right_name, "label": "rotated_right"})
            
            image_upsidedown = rotate(image, -180, preserve_range=True).astype(np.uint8)
            image_upsidedown_name = "up_down" + image_name
            imsave(join("data", "images", image_upsidedown_name), image_upsidedown)
            new_images.append({"fn": image_upsidedown_name, "label": "upside_down"})
            
        elif label == "rotated_left":
            image_upright = rotate(image, -90, preserve_range=True).astype(np.uint8)
            image_upright_name = "left_up" + image_name
            imsave(join("data", "images", image_upright_name), image_upright)
            new_images.append({"fn": image_upright_name, "label": "upright"})
            
            image_right = rotate(image, -180, preserve_range=True).astype(np.uint8)
            image_right_name = "left_right" + image_name
            imsave(join("data", "images", image_right_name), image_right)
            new_images.append({"fn": image_right_name, "label": "rotated_right"})
            
            image_upsidedown = rotate(image, -270, preserve_range=True).astype(np.uint8)
            image_upsidedown_name = "left_down" + image_name
            imsave(join("data", "images", image_upsidedown_name), image_upsidedown)
            new_images.append({"fn": image_upsidedown_name, "label": "upside_down"})
            
        elif label == "rotated_right":
            image_upright = rotate(image, 90, preserve_range=True).astype(np.uint8)
            image_upright_name = "right_up" + image_name
            imsave(join("data", "images", image_upright_name), image_upright)
            new_images.append({"fn": image_upright_name, "label": "upright"})
            
            image_left = rotate(image, 180, preserve_range=True).astype(np.uint8)
            image_left_name = "right_left" + image_name
            imsave(join("data", "images", image_left_name), image_left)
            new_images.append({"fn": image_left_name, "label": "rotated_left"})
            
            image_upsidedown = rotate(image, -90, preserve_range=True).astype(np.uint8)
            image_upsidedown_name = "right_down" + image_name
            imsave(join("data", "images", image_upsidedown_name), image_upsidedown)
            new_images.append({"fn": image_upsidedown_name, "label": "upside_down"})
            
        elif label == "upside_down":
            image_upright = rotate(image, 180, preserve_range=True).astype(np.uint8)
            image_upright_name = "down_up" + image_name
            imsave(join("data","images", image_upright_name), image_upright)
            new_images.append({"fn": image_upright_name, "label": "upright"})
            
            image_left = rotate(image, 270, preserve_range=True).astype(np.uint8)
            image_left_name = "down_left" + image_name
            imsave(join("data","images", image_left_name), image_left)
            new_images.append({"fn": image_left_name, "label": "rotated_left"})
            
            image_right = rotate(image, 90, preserve_range=True).astype(np.uint8)
            image_right_name = "down_right" + image_name
            imsave(join("data", "images",image_right_name), image_right)
            new_images.append({"fn": image_right_name, "label": "rotated_right"})
            
    return new_images

# Folder "data/images" must be empty to run the cell bellow!

In [9]:
new_images = data_augmentation(df)
shuffle(new_images)
df = pd.DataFrame(new_images)
df.head()

                                         fn          label
0  down_left86-28987586_1917-03-28_1948.jpg   rotated_left
1  left_down60-17051360_1988-08-04_2011.jpg    upside_down
2           63-33314263_1984-06-21_2009.jpg  rotated_right
3  right_left14-6093414_1980-11-03_2013.jpg   rotated_left
4            54-1421654_1933-08-27_2011.jpg        upright

In [10]:
df.to_csv("data/name_images.csv")